//One of one of our referral constant is in the userConstants

export const ALL_REFERRAL_REQUEST = "ALL_REFERRAL_REQUEST";
export const ALL_REFERRAL_SUCCESS = "ALL_REFERRAL_SUCCESS";
export const ALL_REFERRAL_FAIL = "ALL_REFERRAL_FAIL";
export const UPDATE_REF_PAYOUT_REQUEST = "UPDATE_REF_PAYOUT_REQUEST";
export const UPDATE_REF_PAYOUT_SUCCESS = "UPDATE_REF_PAYOUT_SUCCESS";
export const UPDATE_REF_PAYOUT_FAIL = "UPDATE_REF_PAYOUT_FAIL";
export const UPDATE_REF_PAYOUT_RESET = "UPDATE_REF_PAYOUT_RESET";
export const REF_PAYOUT_REQUEST = "REF_PAYOUT_REQUEST";
export const REF_PAYOUT_SUCCESS = "REF_PAYOUT_SUCCESS";
export const REF_PAYOUT_FAIL = "REF_PAYOUT_FAIL";
export const DELETE_REFERRAL_REQUEST = "DELETE_REFERRAL_REQUEST";
export const DELETE_REFERRAL_SUCCESS = "DELETE_REFERRAL_SUCCESS";
export const DELETE_REFERRAL_FAIL = "DELETE_REFERRAL_FAIL";